// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBe10gcYQCgHXpuVLMsHNKCRz2AQYwW8',
    appId: '1:1061357051215:web:612cda416f5be70b44b93a',
    messagingSenderId: '1061357051215',
    projectId: 'projectpitwo-ctrlreal',
    authDomain: 'projectpitwo-ctrlreal.firebaseapp.com',
    storageBucket: 'projectpitwo-ctrlreal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1DPq8Iv42Q1W2ocipT8pZRz3ZISntdY',
    appId: '1:1061357051215:android:e50cc710e81349dc44b93a',
    messagingSenderId: '1061357051215',
    projectId: 'projectpitwo-ctrlreal',
    storageBucket: 'projectpitwo-ctrlreal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGwzpMQFi0WcuA8g2dJsKGx8YNqZKcK9Q',
    appId: '1:1061357051215:ios:1b2d6ca7ff9db83f44b93a',
    messagingSenderId: '1061357051215',
    projectId: 'projectpitwo-ctrlreal',
    storageBucket: 'projectpitwo-ctrlreal.appspot.com',
    iosClientId: '1061357051215-09ng7u14vjld6rouhcc1ovs0uo1p4uhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctrlReal',
  );
}
