// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMeHv0X9amIvt7WynMgsun2Q9S5E-_iFs',
    appId: '1:483870613068:web:a88f2b4d9a8d4185fc9ee9',
    messagingSenderId: '483870613068',
    projectId: 'projectpi-ctrlreal',
    authDomain: 'projectpi-ctrlreal.firebaseapp.com',
    storageBucket: 'projectpi-ctrlreal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4BWukiJYsfqaCbXkPeyegyv2tXm9Hus',
    appId: '1:483870613068:android:15c85c51d8bb3249fc9ee9',
    messagingSenderId: '483870613068',
    projectId: 'projectpi-ctrlreal',
    storageBucket: 'projectpi-ctrlreal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbPvVG5ccGm8OGLu823Q5bhafaXtC8Lgk',
    appId: '1:483870613068:ios:9ce5f354695aae51fc9ee9',
    messagingSenderId: '483870613068',
    projectId: 'projectpi-ctrlreal',
    storageBucket: 'projectpi-ctrlreal.appspot.com',
    iosClientId: '483870613068-36u0tv29jh0nc2n9pve2f1o4n2f2uhid.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctrlReal',
  );
}
